sudo: required
language: ruby
rvm:
- 2.3.0
rails:
- 5.0.0
before_install:
- bundle update
- bundle install
before_script:
- cp config/database.travis.yml config/database.yml
- rake db:create
- rake db:migrate
script:
- bin/rails db:environment:set RAILS_ENV=test
- bundle exec rake --trace
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
env:
  matrix:
    secure: juIsNf02jt+yVuz0Y31UH0fcQoAW0vI4H9x0UEsAWSogsOBUUjDBevfQvSV9Z12jgvY5R0MnpWx8wbcVzbbEQ32tF+wDkv931Ja0kYQjN97dPiD3VRSTnKf7Zf5xsb2d66BI2nGgtQTor4V1UdI/topc+++VI1LncVJTsKdP8yPgYie0gxvvnfy+a2N/4e/Rae7uWO5u+l/Hdl0n1bTQO06b3m3ghBRA7XdPGPNuOq3lMZTEfx76MZBUQlm+cc7OpFJmWHuxT0eY9gOhrGFAM0Ssj/m95qKL1cC6GuzWwIQtlCIQoJS1tGK1po4/j6y6Oi0ks4JWePI9HTGuFaz1S1TcBFVFoTVSDD0z0VYIBmqrZhrcV699gRQCMuRRSd9K6A2F995dHNJCY1UAQ9IIsrBkEiXcZQV8h80ekH8tgJjzf1SkE3I+e2VLJji0jP56yni+34mOOFjiHYlgpDj81lX0XJK/6rEH7bK+BtlUpfrMfRN+7GN9U/3ZE8LLQFmv8daJgdLnmov2dfPl4+fYkuOe/SpsCsye/0NSf1iTNmUQek+a33fSiu2aBvGHy5RgpBF6DYLOzWrg6PTIwqo+UYzFoY8JBJWUbqZB12YYTU8JoKzyS+S6rPLqY0JIsSr7ohUQm9Z5Bk89FMu+f4eRubyZt3PgrHksaabgIxz0XAk=
deploy:
  - provider: heroku
    api_key:
      secure: W8lsU9ACB7magwn+RP6eWc7miB9WKg4aTlQdEeAHH0SvUz9u8T3JZaSOZcAmROdrA6uBRdCtKoxzk735bvcYL/+FOs2wrepie6NgETzDvBdBrDPClGleW413OUK0wBhxfPStynZ9EqIYl9lrXonpGIAS69rddHOfsvm418c/X0RMyjETer83tfuTv1XCoxISFTZYsLZP8p6LkSI5bzfBpkxb/VpUVOTKZPtYI1Y/znMM+NmjeHJKEZr2ft67ZhiiNXKY+5YuyCwvmCuYNFglfIbo2qHJ+gYwGo27AYSe9jPFRzf/ogF1TrPeLjCTkgWxYwViAPAE8Ts/r/0oBaUChqLwjLTeWbRL0FHZ1bJx4Xr/FAGI+SAnP7Ahlb5Gv7DtWlGnvucgM5ypxmUR6bq6nz0A0zQPNB3O3Yn0MVnAFnqJ3thTWUUVBQTAQLUcwyUz0zOIx7MHiMlvXvaJ6VZ0KKmMavDDbkCLcexkAskFt1wf7R2zuQbiPNzQOA9DHsd2o4eckncuMsGUDazkpWESFXpt0RZHMNtab8u+A75rFLP5ra3lgBY11JM4p2KGfy1oJ8QQWV825Idc6NDy+tpRZx40jebPuzrEyNPbkDeoUKaTjl9uzAuF+QEGFTWWow1lVayn1iiCVyZSxb2UnOj//U4ndbc8g/v/zLqa8tQyV3s=
  - provider: elasticbeanstalk
    app: trello-stats-getter # Elastic Beanstalk app name
    env: trelloStatsGetter-env # Elastic Beanstalk env name
    bucket_name: elasticbeanstalk-ap-southeast-2-dius-dev-e-iysbvnd8nx # S3 bucket used by Elastic Beanstalk
    region: ap-southeast-2
    access_key_id:
      secure: "jsBuMYMbihtaQGNnbFx7L/rYbA17EDHucnTs5WOcJ04n7xtba6OaJXwhyzLOPSdleaXkp2V2xlKL3vVEpiRcTnbg+aDF4q14mYJZGIpBUztav7u3aSMA27dhGcGCNT1APK940XlgmVpz7YiTccU+BILPVLaKlsneq65dz4js+wr4azGmmCaOeI1nTLLnAe77iJFkPOQNrPPdbI00hCZ5JT5P/EqYg+/YnwDf2J7m8OmrIFCAeui7oDYG3wojnEl8dqcmoFZeQcDozR9Hpx1vKF95O88EYCHPjX86w5DXPHn7OtSu3y1vaxcGTdP/2tTNFx+SaPH/muqhbrYp8thK8KBNOUeBtbYMewBgRkxePSxj2nALtvHjD5eOTp174JhTo6APQWWF9WQGAljZ5LdX4SUyP8hoLc9n/UAzS0aKy/63vGayPXhuGzCDCWKp9IOf+P/GRJFCWv2joVBO7PAT1X4pvfjuBBKxK5WZ2RNHk8DBZC4FNilwiPduD48R/jGm0zXdtbV+I3q6HoD96/qUW+nTEOIEpYA837OqcYGKX0vhVQ+Tkme4BRM8ddkADqCLhF5Su53o5uJ03MUQXROYa3tXL/oA/wIX4d1tVSZbVJ2CkjNznsUCx+fJCV906Kt9EbFIzhHuOCjG8NSwfdzxahC8cwUfUlhf6ssRiCU7spA="
    secret_access_key:
      secure: "e/ZvtNSHkiLz8i2HJVdNz/VXpDp1ML47Tv45gFSSYGcg5cBbEl+QeyI8oFcbjk6tRxwr8HsK+/zubVUTF2ptMztgyxVoALt22sqt3T8uRjA6qlkuT1HtF/YjRIqSt0HGSOa/oxbJDHQsyUmLXj122Lq57Ue8KvF8yJ6Uosqou3TSkYDPd38nIlEGHjDMLjsaNhCxPLRQobSN30A6Y2+m64M5n3aBXxd//x5o/16M2HsidzaB/fNdDZ8qNlkCniDlq9Z8cg4WhZselI159K27dZNk3fu0tHmBw/ik+hmxzn1thTeGLXk9UTG87OaWxlO/lYVc8hxtpLcYwvnbpE0faxfLyhRC5wockT9JQSRU/5JQr367UlnqXgBkGwmZ35TIJy1fJf4EqH+D6inoybmTWR6d+B4PWzI11KluQH2cW5MWxvPf8PdK3MLS+9sgdfmvQNXpbSJV4V0bCSfhHCYGqubPBepQEAnqRnKLRmp1Z2tzbOgG4uyMMYoU2AvQnV1h3yBdHncITnzJtg8q0xhsff1KIs2aKkssbgmOt5sJYDCNLlj0pKRv6hZzxLCXHFX0dDHQZOQa+xP0V1YOruzjsTBsjLOF6PVM2FW9N9BDgaD2gZPacAoRuKCg+OnRVb4XDT6So4Gto0awUGs8GiR2vRsd5u1zUnDQa028R6tLQ1w="
    on:
      branch: production
