branch-defaults:
  master:
    environment: trelloStatsGetter-env
    group_suffix: null
global:
  application_name: trello-stats-getter
  default_ec2_keyname: null
  default_platform: Ruby 2.3 (Puma)
  default_region: ap-southeast-2
  profile: eb-cli
  sc: git
