development:
  adapter: postgresql
  encoding: utf8
  database: trello_dev
  username: trello
  password: trello

test:
  adapter: postgresql
  encoding: utf8
  database: trello_test
  username: trello
  password: trello

production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

cucumber:
  adapter: sqlite3
  database: db/cucumber.sqlite3
  pool: 5
  timeout: 5000